# delete all content in WINEPREFIX directories

rm -rf "../TUE/rFactor/WP"
rm -rf "../TUE/WP"
rm -rf "../TUE/NR2003/INSTALL/NASCAR_Racing_2003_Season_ISO/WP"
rm -rf "../TUE/NR2003/WP"
rm -rf "../WED/WP"
rm -rf "../WED/chessmaster/WP"
rm -rf "../SAT/BMS435/WP"
rm -rf "../SAT/WP"
rm -rf "../FRI/WP"
rm -rf "../THU/BattleOfBritain/WP"
rm -rf "../THU/MigAlley/WP"
rm -rf "../THU/FS9/WP"
rm -rf "../THU/SDOE/WP"
rm -rf "../MON/bb12/WP"
rm -rf "../MON/omar/WP"
rm -rf "../MON/WP"
rm -rf "../SUN/WP"
mkdir "../TUE/rFactor/WP"
mkdir "../TUE/WP"
mkdir "../TUE/NR2003/WP"
mkdir "../WED/WP"
mkdir "../WED/chessmaster/WP"
mkdir "../SAT/BMS435/WP"
mkdir "../SAT/WP"
mkdir "../FRI/WP"
mkdir "../THU/BattleOfBritain/WP"
mkdir "../THU/MigAlley/WP"
mkdir "../THU/FS9/WP"
mkdir "../THU/SDOE/WP"
mkdir "../MON/bb12/WP"
mkdir "../MON/omar/WP"
mkdir "../MON/WP"
mkdir "../SUN/WP"

