clear
echo "To start the mental math quiz:"
echo ""
echo "1. At the ubuntu command prompt, type: sage"
echo ""
echo "2. At the sage prompt, type: load(\"quiz.sage\")"
echo ""
echo "Type your answers as:  answer(<your answer here>)"
echo "Example:"
echo "Question: What is 16 * 12?"
echo "Answer: answer(192)"
echo ""
echo "Note: for improved graphics, replace step 1 above with"
echo "1a. at the ubuntu prompt, type: sage --notebook"
echo "1b. when the notebook window opens in the browser, at the upper"
echo "right select \"New\", then \"SageMath 9.5\""
echo "1c. In the input cell type load(\"quiz.sage\")"
echo "1d. select \"+\" to create a new input cell, then type"
echo "answer(<your answer here>)"
echo ""
echo "After the quiz, type exit to leave sage"
