clear
echo "ps-eval: text mode poker equity calculator, works with Texas Hold em, Omaha, Stud, Draw\n"
echo "    Allowed options:"
echo "      -? [ --help ]          produce help message"
echo "      -g [ --game ] arg (=h) game to use for evaluation"
echo "      -b [ --board ] arg     community cards for he/o/o8"
echo "      -h [ --hand ] arg      a hand for evaluation"
echo "      -q [ --quiet ]         produce no output"
echo ""
echo "       For the --game option, one of the follwing games may be"
echo "       specified."
echo "         h     hold'em"
echo "         o     omaha/8"
echo "         O     omaha high"
echo "         r     razz"
echo "         s     stud"
echo "         e     stud/8"
echo "         q     stud high/low no qualifier"
echo "         d     draw high"
echo "         l     lowball (A-5)"
echo "         k     Kansas City lowball (2-7)"
echo "         t     triple draw lowball (2-7)"
echo "         T     triple draw lowball (A-5)"
echo "         b     badugi"
echo "         3     three-card poker"
echo ""
echo "       examples:"
echo "           ./ps-eval acas"
echo "           ./ps-eval AcAs Kh4d --board 5c8s9h"
echo "           ./ps-eval AcAs Kh4d --board 5c8s9h"
echo "           ./ps-eval --game l 7c5c4c3c2c"
echo "           ./ps-eval --game k 7c5c4c3c2c"
echo "           ./ps-eval --game kansas-city-lowball 7c5c4c3c2c"
echo ""
echo "./ps-eval can take a couple minutes to produce output\n"

