sudo ln -s /opt/wine-staging/bin/msidb /usr/bin/msidb
sudo ln -s /opt/wine-staging/bin/msiexec /usr/bin/msiexec
sudo ln -s /opt/wine-staging/bin/notepad /usr/bin/notepad
sudo ln -s /opt/wine-staging/bin/regedit /usr/bin/regedit
sudo ln -s /opt/wine-staging/bin/regsvr32 /usr/bin/regsvr32
sudo ln -s /opt/wine-staging/bin/widl /usr/bin/widl
sudo ln -s /opt/wine-staging/bin/wine /usr/bin/wine
sudo ln -s /opt/wine-staging/bin/wine64 /usr/bin/wine64
sudo ln -s /opt/wine-staging/bin/wine64-preloader /usr/bin/wine64-preloader
sudo ln -s /opt/wine-staging/bin/wineboot /usr/bin/wineboot
sudo ln -s /opt/wine-staging/bin/winebuild /usr/bin/winebuild
sudo ln -s /opt/wine-staging/bin/winecfg /usr/bin/winecfg
sudo ln -s /opt/wine-staging/bin/wineconsole /usr/bin/wineconsole
sudo ln -s /opt/wine-staging/bin/winecpp /usr/bin/winecpp
sudo ln -s /opt/wine-staging/bin/winedbg /usr/bin/winedbg
sudo ln -s /opt/wine-staging/bin/winedump /usr/bin/winedump
sudo ln -s /opt/wine-staging/bin/winefile /usr/bin/winefile
sudo ln -s /opt/wine-staging/bin/wineg++ /usr/bin/wineg++
sudo ln -s /opt/wine-staging/bin/winegcc /usr/bin/winegcc
sudo ln -s /opt/wine-staging/bin/winemaker /usr/bin/winemaker
sudo ln -s /opt/wine-staging/bin/winemine /usr/bin/winemine
sudo ln -s /opt/wine-staging/bin/winepath /usr/bin/winepath
sudo ln -s /opt/wine-staging/bin/wine-preloader /usr/bin/wine-preloader
sudo ln -s /opt/wine-staging/bin/wineserver /usr/bin/wineserver
sudo ln -s /opt/wine-staging/bin/wmc /usr/bin/wmc
sudo ln -s /opt/wine-staging/bin/wrc /usr/bin/wrc
